### ISSUE TITLE
some questions about this

### ISSUE THREAD

**Issue by terrified9** [mikex86/MinecraftEarthRecode#2]
1. Is it playable in the current state?
2. Do you plan adding some "server software"? since i think the original mc earth needed servers in different countries
3. if this ever comes to a "mature state", would it be possible to publish somewhere (g play, etc)? or mojang copyright wouldnt allow?
4. how do i build it? (i see theres no gradleW stuff)
thanks!

**Comment by mikex86** [comment]
1. Well, for now you can run around in a static super flat world. The world system still needs some work before more stuff can be added. I'm not really actively developing this project, which I kind of started as a joke. But considering that Minecraft Earth is dead, I see how there could be a demand for this now.

2. The game is still in a pretty rudimentary state, but multiplayer support will be integrated as soon as it makes sense to do so. Servers for different countries would assert that there is some form of centrally hosted multiplayer all players. Maintaining servers costs money, so multiplayer would work similar to Minecraft Java Edition where you have to either host your own server, or join somebody else's.

3. The project is currently using Minecraft's textures, which could be a problem. I hope Mojang doesn't sue me for a fun little hobby open source project though.

4. You can build the project without a gradle wrapper. Simply install gradle for your operating system, navigate to the directory where you cloned this project and execute "gradle build" (or simply open the project with Android Studio).

**Comment by terrified9** [comment]
thanks for responding! i wish you good luck with your projects.

**Comment by terrified9** [comment]
and yeah, you are right i came here because another project trying to revive mc earth dead
